version: 2.1
orbs:
  circleci-cli: circleci/circleci-cli@0.1.9

definitions:
  filters:
    tag_filtering: &tag_filtering
      branches:
        only:
          - develop # use for idev
          - master # use for PRODUCTION
          
        ignore: /.*/ # ignore other trash branches
      tags:
        only:
          - /^[0-9]+(\.[0-9]+)*$/ # use for PRODUCTION
          - /^v[0-9]+(\.[0-9]+)*$/
          # ignore other trash tags