docker:
  - image: cimg/aws:2022.06
environment:
  AWS_ECR_REPOSITORY: 'franky_test_1'
steps:
  - checkout
  - aws-cli/setup:
      role_arn: "arn:aws:iam::${AWS_ACCOUNT_ID}:role/OIDC_CIRCLECI_FRANKY_ORG_ROLE"
      region: ${AWS_REGION}
      # optional parameters
      profile_name: "OIDC_PROFILE"
      role_session_name: 'hello world'
      session_duration: '1800'
  - run:
      name: Run-STS-Command
      command: |
        # must use same profile specified in the step above
        aws sts get-caller-identity --profile "OIDC_PROFILE"
  - run:
      name: Log-into-AWS-ECR
      command: |
        # must use same profile specified in the step above       
        aws ecr get-login-password --profile "OIDC_PROFILE"
  - run:
      name: Log-into-AWS-ECR
      command: |
        # must use same profile specified in the step above       
        aws ecr get-login-password --region ${AWS_REGION} --profile "OIDC_PROFILE" | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
  - run:
      name: List-ECR-Repositories
      command: |
        # must use same profile specified in the step above
        aws ecr describe-repositories --profile "OIDC_PROFILE"
  - run:
      name: build docker image
      command: |
        docker build -t ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${AWS_ECR_REPOSITORY}:${CIRCLE_SHA1} .
  - run:
      name: push docker image
      command: |
        docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${AWS_ECR_REPOSITORY}:${CIRCLE_SHA1}
      