version: 2.1

# Define the parameter `target_env` dynamically at pipeline level
parameters:
  target_env:
    type: string
    default: ''  # The environment (beta | staging | production)

# Setup job that dynamically determines `target_env`
jobs:
# Main job that uses the dynamically set `target_env`
  my_job:
    docker:
      - image: circleci/python:3.8
    steps:
      - run:
          name: "Print all environment variables"
          command: env
      - run:
          name: "Deploying to target_env"
          command: echo "Deploying to $TARGET_ENV environment"

# Workflow definition
workflows:
  my_workflow:
    jobs:
      - my_job
        