version: 2.1
setup: true

jobs:
# Main job that uses the dynamically set `target_env`
  my_job:
    docker:
      - image: circleci/python:3.8
    steps:
      - run:
          name: "Print all environment variables"
          command: env
      - run:
          name: "Deploying to target_env"
          command: echo "Deploying to $TARGET_ENV environment"
  hello_world:
    docker:
      - image: circleci/python:3.8
    steps:
      - run:
          name: "Print Hello World"
          command: echo "Hello, World!"

# Workflow definition
workflows:
  my_workflow:
    jobs:
      - my_job
      - hello_world
  only_hellworld:
    jobs:
      - hello_world
