version: 2.1

setup: true

orbs:
  circleci-cli: circleci/circleci-cli@0.1.9
  continuation: circleci/continuation@1.0.0


definitions:
  filters:
    allow_run_setup_job_filter: &allow_run_setup_job_filter
      branches:
        only:
          - develop # use for idev
          - main # use for PRODUCTION
          - master # use for PRODUCTION
          
        ignore: /.*/ # ignore other trash branches
      tags:
        only:
          - /^[0-9]+(\.[0-9]+)*$/ # use for PRODUCTION
          - /^v[0-9]+(\.[0-9]+)*$/
          # ignore other trash tags

jobs:
  setup:
    executor: circleci-cli/default
    steps:
      - circleci-cli/install
      - run:
            name: Pack
            command: circleci config pack .circleci/shared > .circleci/generated-config.yml
      - run:
          name: echo config.yaml file
          command: cat .circleci/generated-config.yml
      - run:
            name: Validate
            command: circleci config validate .circleci/generated-config.yml # Money Forward org-id
      - continuation/continue:
          configuration_path: .circleci/generated-config.yml
  helloworld_job:
    executor: circleci-cli/default
    steps:
      - run:
          name: echo helloworld
          command: echo "Hello World"

# Workflow definition with branch filters
workflows:
  branch_master_testing_regex:
    when: 
      and:
        - matches: 
            pattern: /^mas.*$/
            value: << pipeline.git.branch >>
    jobs:
      - hello_world
  branch_main_testing_euqal:
    when: 
      and: # All must be true to trigger
      - equal: [ main, << pipeline.git.branch >> ]
    jobs:
      - hello_world

  setup_flow:
    jobs:
      - setup:
          filters: *allow_run_setup_job_filter
