version: 2.1

setup: true

jobs:
  # Main job that uses the dynamically set `target_env`
  my_job:
    docker:
      - image: circleci/python:3.8
    steps:
      - run:
          name: "Print all environment variables"
          command: env
      - run:
          name: "Deploying to target_env"
          command: echo "Deploying to $TARGET_ENV environment"

  # Separate job to print "Hello, World!"
  hello_world:
    docker:
      - image: circleci/python:3.8
    steps:
      - run:
          name: "Print Hello World"
          command: echo "Hello, World!"

# Workflow definition with branch filters
workflows:
  my_workflow:
    jobs:
      - my_job
    # Example filter to run only on `main` branch
    when: << pipeline.git.branch == "main" >>

  only_helloworld:
    jobs:
      - hello_world
    # Example filter to run only on `dev` branch
    when: << pipeline.git.branch == "dev" >>