
when: 
  and:
    - matches: 
        pattern: /^v[0-9]+(\.[0-9]+)*$/
        value: << pipeline.git.tag >>
jobs:
  - hello_world_job_shared:
      filters:
        tags:
          only: /.*/
            