
when: 
  and:
    - matches: 
        pattern: /^v[0-9]+(\.[0-9]+)*$/
        value: << pipeline.git.tag >>
jobs:
  - job_hello_world_shared:
      filters:
        tags:
          only: /.*/
  - job_hello_world_2_shared # this job won't run because its filter is not satisfied for tags
    